import app.api.routes.beds as beds
import app.api.routes.login as login
import app.api.routes.users as users
import app.api.routes.admins as admins
import app.api.routes.doctors as doctors
import app.api.routes.patients as patients
import app.api.routes.documents as documents
import app.api.routes.specialities as specialities
import app.api.routes.consultations as consultations
import app.api.routes.hospitalizations as hospitalizations
