from app.models.users_info import UsersInfo
from app.models.user_roles import UserRoles
from app.models.patient_info import PatientInfo
from app.models.specialities import Specialities
from app.models.doctor_specialities import DoctorSpecialities
from app.models.beds import Beds
from app.models.beds_used import BedsUsed
from app.models.medical_consults import MedicalConsults
from app.models.hospitalizations import Hospitalizations
